### ISSUE TITLE
Notarization

### ISSUE THREAD

**Issue by cannonsmith** [miyako/4d-plugin-system-notification#1]
Hi Miyako,

Yesterday you were able to make some changes to the cURL FTP plugins that allows it to be notarized after Apple's recent changes. Would it be possible for you to update this plugin in a similar way?

Thanks you.

**Comment by miyako** [comment]
I can recompile and notarise but I do not have time to thoroughly test.
it is possible that the plugin malfunctions even though it passes notarisation.

**Comment by miyako** [comment]
https://github.com/miyako/4d-plugin-system-notification/releases/tag/2.2.v18

**Comment by cannonsmith** [comment]
Thank you. I haven't verified the functionality, but it now signs correctly. Hopefully it will also notarize, but I have a few other plugins to deal with before I'll know for sure.
Thanks.

**Comment by miyako** [comment]
any of them mine?

**Comment by cannonsmith** [comment]
Nope. :-) They are:

- API Pack
- Text Metrics Plugin (a custom on by Rob Laveaux)
- Win32API

If there is a change I can make myself without contacting them, I’d be grateful to know what that is as well.

Thanks.

--
Cannon Smith
Synergy Farm Solutions Inc.
<cannon@synergyfarmsolutions.com>
<www.synergyfarmsolutions.com>

**Comment by miyako** [comment]
technically it is possible to code sign and notarise a plugin created by someone else,
but it feels very bad.

**Comment by miyako** [comment]
example 

https://github.com/miyako/4D-Win32API/releases/tag/8.3.v18

**Comment by cannonsmith** [comment]
Thank you for doing the Win32API one. Much appreciated.
