### ISSUE TITLE
Fails with v19/Windows 11?

### ISSUE THREAD

**Issue by ThomasMaul** [miyako/4d-plugin-system-notification#3]
Customer reported that the plugin is not called anymore at all in:
https://discuss.4d.com/t/plugin-system-notification-wie-benutzen/22045

Auto translation:
Unfortunately I can't get it to work. I would have thought that you have to activate the event handler in the ON STARTUP first, for example:

$vl_ok:=SN Set method ("SYSTEM_EVENT").
And then this handler is called automatically when you lock the screen or shutdown Windows. So I wrote the following in the SYSTEM_EVENT method:

C_LONGINT($1)
TEXT TO DOCUMENT(System folder(Desktop)+"test.txt";String($1))
If I then lock the screen or shut down Windows while the handler is running, then a file "test.txt" should appear on the desktop. But nothing appears.

(tested with 4Dv18.3 and 4Dv19.1 Windows)

I tried myself with v19.1 and Windows 11 and had the same result

**Comment by miyako** [comment]
reading the source I see several issues:

* the way to obtain the MDI reference assumes **Altura** on Windows
* there is no effort to support SDI mode on Windows
* some UI code is executed not in the main thread on Mac 

I can address 1 and 3 because they are regressions but I would rather leave 2 as not implemented.

**Comment by miyako** [comment]
done in 4.0.0

**Comment by miyako** [comment]
for comparison:[ 4.0.1](https://github.com/miyako/4d-plugin-system-notification/releases/tag/4.0.1) is basically the same but calls the init/deinit code in the main thread on Mac only.

**Comment by miyako** [comment]
as specifically mentioned in the README, lock detection is for Mac only.
