### ISSUE TITLE
4.1.0 Crashing macOS

### ISSUE THREAD

**Issue by cannonsmith** [miyako/4d-plugin-system-notification#6]
I've using version 3.2.0 for sometime. Last week I decided to run 4.1.0 just to be running the latest version. Immediately 4D started crashing on me after open and closing several windows. It seemed to be tied with closing a window. No particular window, though. As long as I opened and then closed random windows, 4D would usually crash within a couple minutes. Reverting back to 3.2.0 fixed the issue.

This was with 4D v18.5 HF2 on macOS 12.3.1 on a 16" MacBook Pro with M1 Max chip. I'm not too worried about a fix and didn't have time to delve into the crash more, but at least wanted to report what I experienced.

**Comment by miyako** [comment]
just a shot in the dark, when you close a window, does that also end a process, and if yes, is it possible that the process name is longer than 31 characters?

**Comment by miyako** [comment]
for comparison, I have extended the buffer size from 33 to 256 in 4.1.1 (mac side only).

if that fixes it for you, I will update the windows side as well.

the 3.x branch is using the v11/v13 SDK, which is fine, but harder to maintain going forward.

**Comment by cannonsmith** [comment]
That's an impressive shot in the dark. :-) It does fit the pattern exactly. I just tried the 4.1.2 build and can't get it to crash anymore, so I'd say it is fixed.

Does the 4.1.2 build have the fix for Windows as well or should I wait for a 4.1.3 before using?

Thanks for your quick work on this.

**Comment by miyako** [comment]
yes 4.1.2 has the same fix for Windows

https://github.com/miyako/4d-plugin-system-notification/releases/tag/4.1.2

**Comment by cannonsmith** [comment]
Perfect. Thank you!
